---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs-operator/