apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- local-path-storage.yaml

configMapGenerator:
- name: local-path-config
  namespace: local-path-storage
  behavior: create
  files:
  - helperPod.yaml
  - config.json
  - setup
  - teardown

generatorOptions:
  disableNameSuffixHash: true
