apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: seaweedfs-operator
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-operator
        namespace: flux-system
  values:
    webhook:
      enabled: false
  #valuesFrom:
  #- kind: ConfigMap
  #  name: seaweedfs-operator-helm-chart-value-overrides
  #  valuesKey: values.yaml # This is the default, but best to be explicit for clarity